### ISSUE TITLE
Not storing settings

### ISSUE THREAD

**Issue by theonedon** [Buzzet/streamdeck-azure-pipeline#1]
The Pipeline ID and Run index values I enter do not get saved.

Also, no matter what Project I use the icons all change when there is an update to 1 of the pipelines.

**Comment by Buzzet** [comment]
> The Pipeline ID and Run index values I enter do not get saved.
> 
> 
> 
> Also, no matter what Project I use the icons all change when there is an update to 1 of the pipelines.

Looking into it

**Comment by theonedon** [comment]
> 

Any luck?

**Comment by RuneORakeie** [comment]
I experience the same issue as OP. Please inform us if you have a chance to look into it. Atm running StreamDeck 6.0.2 (17735) on MacOS 12.6.3

**Comment by Buzzet** [comment]
It is storing the value but not showing them.
For me it works fine, just don't be confused when the value doesn't appear. I'll still fix it in the future.

**Comment by Buzzet** [comment]
Has been fixed. New Update send to Elgato (v1.1) and will available soon.
